version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - redis
    env_file: .env.prod.docker
    environment:
      RAILS_MAX_THREADS: 8
      REDIS_HOST: redis
      REDIS_URL: redis://redis:6379/0
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
