apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - bash
        - -c
        - rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'
        env:
        - name: RAILS_MAX_THREADS
          value: "8"
        - name: REDIS_HOST
          value: redis
        image: "gcr.io/travelnogo/travelnogo-api_web"
        imagePullPolicy: ""
        name: web
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /myapp
          name: web-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0

status: {}
